plugins:
  - rubocop-capybara
  - rubocop-rspec
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec_rails
  - rubocop-thread_safety

inherit_mode:
  merge:
    - Exclude

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "config/**/*"
    - "test/**/*"
    - "spec/**/*"

Layout/LineLength:
  Exclude:
    - "config/**/*"

Style/ClassAndModuleChildren:
  Enabled: true
  EnforcedStyle: nested
  SafeAutoCorrect: true
  Exclude:
    - config/**/*

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Metrics/ClassLength:
  Exclude:
    - "test/**/*"
    - "spec/**/*"