x-bun: &bun
  build:
    context: .
    dockerfile: ./Bun.dockerfile
    args:
      BUN_VERSION: '1.2.18'
  tty: true
  stdin_open: true
  restart: unless-stopped
  volumes:
    - .:/app
    - node_modules_cache:/app/node_modules

x-rails: &rails
  build:
    context: .
    dockerfile: ./Dockerfile.dev
    args:
      RUBY_VERSION: '3.4.1'
  tty: true
  stdin_open: true
  volumes:
    - .:/app
    - node_modules_cache:/app/node_modules

services:
  rails:
    <<: *rails
    command: >
      sh -c "
        rm -f tmp/pids/server.pid
        bin/rails server -b 0.0.0.0 -p 3000
      "
    ports:
      - '3000:3000'
    env_file:
      - .env
  
  js:
    <<: *bun
    command: >
      sh -c "
        bun install
        bun run build --watch
      "
  
  css:
    <<: *bun
    command: >
      sh -c "
        bun install
        bun build:css --watch
      "

volumes:
  node_modules_cache:
