x-assets: &assets
  build:
    context: .
    dockerfile: ./Assets.dockerfile
  restart: always
  volumes:
    - .:/app
    - /app/node_modules

x-rails: &rails
  build:
    context: .
    dockerfile: ./Dockerfile.dev
    args:
      RUBY_VERSION: '3.4.1'
  tty: true
  stdin_open: true
  volumes:
    - .:/app

services:
  rails:
    <<: *rails
    command: >
      sh -c "
        rm -f tmp/pids/server.pid
        bin/rails server -b 0.0.0.0 -p 3000
      "
    ports:
      - '3000:3000'
    env_file:
      - .env
  
  js:
    <<: *assets
    command: yarn build --watch
  
  css:
    <<: *assets
    command: yarn build:css --watch
