services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
      args:
        RUBY_VERSION: '3.4.1'
    volumes:
      - .:/app
    command: >
      sh -c "
        rm -f tmp/pids/server.pid
        bin/rails server -b 0.0.0.0 -p 3000
      "
    tty: true
    stdin_open: true
    ports:
      - '3000:3000'
    env_file:
      - .env
  
  js:
    build:
      context: .
      dockerfile: ./Assets.dockerfile
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
    command: yarn build --watch
  
  css:
    build:
      context: .
      dockerfile: ./Assets.dockerfile
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
    command: yarn build:css --watch
