x-ruby: &ruby
  build:
    context: .
    dockerfile: ./Dockerfile.dev
    args:
      RUBY_VERSION: '3.4.1'
      NODE_MAJOR: '20'
  environment:
    RAILS_ENV: development
    NODE_ENV: development
    HISTFILE: /usr/local/hist/.bash_history
    IRB_HISTFILE: /usr/local/hist/.irb_history
    EDITOR: vi
    YARN_CACHE_FOLDER: /app/node_modules/.yarn-cache
  tmpfs:
    - /tmp
    - /app/tmp/pids
  stdin_open: true
  tty: true
  volumes:
    - .:/app
    - bundle:/usr/local/bundle
    - rails_cache:/app/tmp/cache
    - history:/usr/local/hist

services:
  rails:
    <<: *ruby
    command: >
      sh -c "
        rm -f tmp/pids/server.pid
        bin/rails server -b 0.0.0.0 -p 3000
      "
    depends_on:
      bundler:
        condition: service_completed_successfully
    ports:
      - '3000:3000'
    env_file:
      - .env

  bundler:
    <<: *ruby
    command: >
      bash -c "
        echo 'Running bundler...';
        bundle --version;
        bundle install;
      "
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
  
volumes:
  bundle:
  history:
  rails_cache:
  