plugins:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
  - rubocop-thread_safety
  - rubocop-factory_bot

AllCops:
  NewCops: enable
  TargetRubyVersion: <%= File.read('.ruby-version').strip[/^\d+\.\d+/, 0] %>
  Exclude:
    - 'db/schema.rb'
    - 'Gemfile'
    - 'lib/tasks/*.rake'
    - 'bin/*'
    - 'node_modules/**/*'
    - 'config/puma.rb'
    - 'config/spring.rb'
    - 'config/environments/development.rb'
    - 'config/environments/production.rb'
    - 'spec/spec_helper.rb'
